dagger query << EOF
query {
  trivy {
    check(repository:"https://github.com/dagger/hello-dagger.git", path: "/src") {
      stdout
    }
  } 
}
EOF

dagger query << EOF
query {
  snyk {
    check(token: "TOKEN", repository:"https://github.com/dagger/hello-dagger.git", path: "/src") {
      stdout
    }
  } 
}
EOF

dagger query << EOF
query {
  vuln {
    check(scanner: "trivy", {repository:"https://github.com/dagger/hello-dagger.git", path: "/src"}) {
      stdout
    }
  } 
}
EOF
